# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab  
  workflow_dispatch:
    inputs:
      message:
        description: Commit message
        required: true
        default: Main build ...
      committer_name:
        description: Committer Name
        required: true
      committer_email:
        description: Committer Email
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
     - uses: actions/checkout@v2
     - name: Setup node.js 12
       uses: actions/setup-node@v1
       with:
         node-version: '12.x'
     - name: Install dependencies
       run: npm install.
     - name: Build app
       run: npm run build
     - name: Commit changes
       uses: EndBug/add-and-commit@v7
       with:
         committer_name: ${{ github.event.inputs.committer_name }}
         committer_email: ${{ github.event.inputs.committer_email }}
         message:  ${{ github.event.inputs.message }}

